export const BADGE_IDS = {
  PROFILE_POLISHER_ID: 1,
  EVENT_ENGAGER_ID: 2,
  COMMUNITY_CONTRIBUTOR_ID: 3,
  ANNOUNCEMENT_ADMIRER_ID: 4,
  ACCOMPLISHMENT_ACHIEVER_ID: 5,
  SURVEY_SUBMITTER_ID: 6,
} as const
