export const regions = [
  { value: "northland-region", label: "Northland Region" },
  { value: "auckland", label: "Auckland" },
  { value: "waikato-region", label: "Waikato Region" },
  { value: "bay-of-plenty-region", label: "Bay of Plenty Region" },
  { value: "gisborne-region", label: "Gisborne Region" },
  { value: "hawkes-bay-region", label: "Hawkes Bay Region" },
  { value: "taranaki-region", label: "Taranaki Region" },
  { value: "manawatu-whanganui-region", label: "Manawatū-Whanganui Region" },
  { value: "wellington-region", label: "Wellington Region" },
  { value: "west-coast-region", label: "West Coast Region" },
  { value: "canterbury-region", label: "Canterbury Region" },
  { value: "otago-region", label: "Otago Region" },
  { value: "southland-region", label: "Southland Region" },
  { value: "tasman-region", label: "Tasman Region" },
  { value: "nelson-region", label: "Nelson Region" },
  { value: "marlborough-region", label: "Marlborough Region" },
  { value: "area-outside-region", label: "Area Outside Region" },
]
